services:
  - type: web
    name: n8n-on-render
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
      image: n8nio/n8n:latest
    envVars:
      - key: N8N_BASIC_AUTH_PASSWORD  # Only keep the sensitive one
        generateValue: true
      - key: N8N_TRUST_PROXY  # Keep this here to ensure it's set
        value: true
    port: 5678
